### ISSUE TITLE
ddrv and discord server?

### ISSUE THREAD

**Issue by martysl** [forscht/ddrive#108]
hi what happend to ddrv project in github and discord server related to it?

**Comment by mint1246** [comment]
i wonder it too 
was a really good project

**Comment by emberglazee** [comment]
same..

**Comment by mint1246** [comment]
looking at the thingy tho he still sorta seems to be working on private repositories, who knows, hopefully it will return, even if dev wont update it anymore he should at least make it public so we can still use it and update it in forks

**Comment by algj** [comment]
I have a suspicion that Discord has contacted @forscht to take down the project, especially after Discord has decided to stop the CDN abuse.

**Comment by martysl** [comment]
https://github.com/ImPeekaboo/ddrv
but its not the same...

**Comment by forscht** [comment]
I had to Stop working on it to due legale issues

**Comment by cyosat** [comment]
@forscht can we somehow connect?
