### ISSUE TITLE
[Error] discord api: socket hang up

### ISSUE THREAD

**Issue by emberglazee** [forscht/ddrive#11]
from time to time when uploading large files (>8mb in size) I get an error mid-uploading:
in console `Error: request to https://discord.com/api/v9/channels/XXX/messages failed, reason: socket hang up`
[uploading file with curl](https://github.com/forscht/ddrive/issues/9) `request to https://discord.com/api/v9/channels/XXX/messages failed, reason: socket hang up`
web server actually displays an error only like 20% of the time.

95% of the time that leaves some left over file parts, which just stay there and don't get deleted.
from my observation: `if file uploading speed is too high, the upload pauses after X mb to catch up with uploading the parts to discord, could discord's rate limits be the issue? and if so, is it possible to limit the uploading speed if a file is over 8mb?`

**Comment by forscht** [comment]
Hi @NoNameLmao , Can provide me some error logs? Is your internet connection stable? I have uploaded file with 16 GB size from 1GBps network link and everything worked fine for me.

I have already handled Discord rate limits so it shouldn't be an issue.

**Comment by emberglazee** [comment]
i never had any problems with connection stability (before, atleast) also i am running it on an AWS VPS in germany and there are no issues between me and my VPS so
```error === Begin Error ===
  error ---
  error Error: request to https://discord.com/api/v9/channels/XXX/messages failed, reason: socket hang up
  error method : POST
  error url : /video.mp4
  error Stack: FetchError: request to https://discord.com/api/v9/channels/XXX/messages failed, reason: socket hang up
  error     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@forscht/ddrive/node_modules/node-fetch/lib/index.js:1491:11)
  error     at ClientRequest.emit (node:events:539:35)
  error     at TLSSocket.socketOnEnd (node:_http_client:478:9)
  error     at TLSSocket.emit (node:events:539:35)
  error     at endReadableNT (node:internal/streams/readable:1345:12)
  error     at processTicksAndRejections (node:internal/process/task_queues:83:21)
  error ---
  error === End Error === +0ms

**Comment by emberglazee** [comment]
I have 60Mbps internet and about 60ms ping to the VPS
that error pops up at usually about 30mb to 40mb uploaded

**Comment by forscht** [comment]
@NoNameLmao I think it's temporary Discord API issue. Can you wait for 24 hours and try again? Since how long you have been using this?
![image](https://user-images.githubusercontent.com/59018146/171288635-aeebfa36-c569-4107-95b2-1ad5b8891e1b.png)

**Comment by emberglazee** [comment]
about 4 hours ago from now

**Comment by forscht** [comment]
@NoNameLmao Give me sometime I will test my side and update you. Mean while can you run this code in local and see if you're getting same error?

**Comment by emberglazee** [comment]
alright, i'll do that now

**Comment by emberglazee** [comment]
> I think it's temporary Discord API issue.

looks like everything is working now. gotta love how problems sometimes get resolved by themselves

**Comment by forscht** [comment]
> > I think it's temporary Discord API issue.
> 
> looks like everything is working now. gotta love how problems sometimes get resolved by themselves

Yeah, Just Discord thing :wink:
