### ISSUE TITLE
[Feature Request] 50/100MB files if there are boosts in the discord server

### ISSUE THREAD

**Issue by sidanya** [forscht/ddrive#13]
Maybe check availability or make it possible to resize blocks. This will make uploading large files much faster

**Comment by megahypercat** [comment]
You probably don't want to do this, because then when they delete that server and ban your accounts, you'll actually lose something.

**Comment by ethan-xd** [comment]
> You probably don't want to do this, because then when they delete that server and ban your accounts, you'll actually lose something.

i get this point but it should still be an option for people who want to risk that

**Comment by forscht** [comment]
@ethan-xd @idanyas I will add this feature in upcoming release.

**Comment by forscht** [comment]
@idanyas @ethan-xd Now you can define custom chunk size https://github.com/forscht/ddrive/blob/v3.6.0/README.md#api-usage
