### ISSUE TITLE
Files not cleaned up when reloading page

### ISSUE THREAD

**Issue by UnlimitedBytes** [forscht/ddrive#15]
When you upload a bigger file (depending on internet speed ~1GB) and reload during the upload the bot crashes and has only one part of the file in the browser.

**Comment by forscht** [comment]
@UnlimitedBytes Sorry for late reply, can you please attach the logs you're seeing on your console?

**Comment by forscht** [comment]
@UnlimitedBytes , Fixed this issue in new release
