### ISSUE TITLE
Server error when uploading file.

### ISSUE THREAD

**Issue by Spagett1** [forscht/ddrive#16]
upon uploading a 24mb file i get an internal server error 
![image](https://user-images.githubusercontent.com/77225642/179772400-bb83aeee-0a54-4526-99fb-374a3225afec.png)
smaller files seem to work, this is the error
```
  discordFS >> [ADD] in progress : /New Folder/01 Paint It, Black.flac +7s
  error === Begin Error ===
  error ---
  error Error: The user aborted a request.
  error method : POST
  error url : /New Folder/01 Paint It, Black.flac
  error Stack: AbortError: The user aborted a request.
  error     at abort (/usr/lib/node_modules/@forscht/ddrive/node_modules/node-fetch/lib/index.js:1448:16)
  error     at AbortSignal.abortAndFinalize (/usr/lib/node_modules/@forscht/ddrive/node_modules/node-fetch/lib/index.js:1463:4)
  error     at AbortSignal.dispatchEvent (/usr/lib/node_modules/@forscht/ddrive/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
  error     at abortSignal (/usr/lib/node_modules/@forscht/ddrive/node_modules/abort-controller/dist/abort-controller.js:52:12)
  error     at AbortController.abort (/usr/lib/node_modules/@forscht/ddrive/node_modules/abort-controller/dist/abort-controller.js:91:9)
  error     at Timeout.<anonymous> (/usr/lib/node_modules/@forscht/ddrive/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.js:115:53)
  error     at listOnTimeout (node:internal/timers:564:17)
  error     at process.processTimers (node:internal/timers:507:7)
  error ---
  error === End Error === +3m
  ```

**Comment by forscht** [comment]
@Laar3 , This could be due to bad network or discord API issue. Are you still facing this issue?

**Comment by forscht** [comment]
@Laar3 Colsing for now, please reopen if you're still facing this issue.

**Comment by Spagett1** [comment]
> @Laar3 , This could be due to bad network or discord API issue. Are you still facing this issue?

Yeah im still having the issue, it may be due to my internet being quite slow in upload speed, maybe its timing out? If thats it would there be a way to increase the timeout?

**Comment by forscht** [comment]
@Laar3, Not sure that's possible. Since I am using readymade Discord API library made by discord.js devs. I will check if it's possible to solve by tweaking library params. I have uploaded 4000GB+ of data and never faced this issue.

**Comment by Spagett1** [comment]
ah thats weird, if there are any logs that can help let me know

**Comment by forscht** [comment]
@Laar3 , You can now add custom timeout limit - https://github.com/forscht/ddrive/blob/v3.6.0/README.md#api-usage

**Comment by Spagett1** [comment]
Awesome! sorry im not familiar with npm or js, where is the file that i can edit that value stored? thanks
