### ISSUE TITLE
Error: Cannot find module 'node:buffer'

### ISSUE THREAD

**Issue by pmint05** [forscht/ddrive#18]
When I run `ddrive --token <bot token> --channelId <guild channel id>`, I had this error
![image](https://user-images.githubusercontent.com/52208732/181681528-14bf3c0c-b56d-4b83-b378-4a1330eed04b.png)

Has anyone had this error? And has anyone been able to fix this?

**Comment by aiko-chan-ai** [comment]
node v16 ?

**Comment by forscht** [comment]
@pmint05 Update the node version to latest 16.x version. It will fix the issue.

**Comment by pmint05** [comment]
> @pmint05 Update the node version to latest 16.x version. It will fix the issue.

Thanks, I fixed this!

**Comment by pmint05** [comment]
> node v16 ?

Em quên chưa check, thanks bác

**Comment by aiko-chan-ai** [comment]
> Em quên chưa check, thanks bác

Kiểm tra trc khi mở issue nhé
