### ISSUE TITLE
how to make this service available all the time

### ISSUE THREAD

**Issue by Ekramhadidi** [forscht/ddrive#22]
i managed to run this app on localhost and upload files. the service only works when i launch it from my local machine using cmd. but im planning on using it to share my uploaded files with others. which would require this service to be running all the time on dedicated machines to keep the downloads online. 
i tried deploying the api code into replit and it worked. but im still running into the risk of having my respiratory interface out there in the open using free plan.  and i don't know what heroku offers in that regard because i couldn't figure out how to run the script on it.
are there any other services that could freely run my scrript all the time privately other than these 2 options?

**Comment by forscht** [comment]
1. Heroku - Free for next 2 months
2. Replit - Forever free
3. GCloud - Free account for 3 months. (require credit card)
4. Oracle cloud - Forever free but hard to setup. (require credit card)
5. AWS - 1 Year free (require credit card)
