### ISSUE TITLE
SUGGESTION | authentication system so it can be hosted on a vps without the fear of data being leaked

### ISSUE THREAD

**Issue by lunyaUwU** [forscht/ddrive#23]

**Comment by sidanya** [comment]
There's already a HTTP authorization here. Or what do you mean?

**Comment by canjbfeeltheesemuffins** [comment]
no idea what he means, owners can see anything on their vps

**Comment by UnlimitedBytes** [comment]
But extended this would be cool if we combine it with a user system so multiple users can use the same instance

**Comment by forscht** [comment]
Implementing user system will bit overkill for this project. User system will require database, I am trying to keep this project lightweight and dependency free.
