### ISSUE TITLE
Suggestion - Being able to connect to Ddrive using an ftp client

### ISSUE THREAD

**Issue by Dycool** [forscht/ddrive#24]
Its not that I dont like the html page, but would be really useful.

**Comment by sidanya** [comment]
I think this is very hard technically, but it would be cool. I'm also wondering if it's even possible to turn pages into an nginx-like "autoindex", like this:

![](https://www.keycdn.com/img/support/nginx-directory-index-listing-lg.webp)

**Comment by barthofu** [comment]
Would be incredible!

**Comment by forscht** [comment]
Not sure if it's possible. But I will look into this once I get time.

**Comment by Dycool** [comment]
With this new v4 version, is this possible now?

**Comment by UnlimitedBytes** [comment]
This wasn't implemented in v4.

**Comment by skygunner** [comment]
FTP has been implemented in those projects:
https://github.com/fr34kyn01535/discord-fs with pacakge simple-ftpd
also
https://github.com/pixelomer/discord-fs with pacakge ftp-srv

**Comment by forscht** [comment]
I have implemented this in another project, this will get job done while using fraction of memory compared to ddrive 
https://github.com/forscht/ddrv
