### ISSUE TITLE
deploy to Heroku button?

### ISSUE THREAD

**Issue by cboRD181** [forscht/ddrive#26]
Couldn't figure out how to deploy to heroku, any chance this feature could be added for those of us less familiar with the service?

**Comment by Ekramhadidi** [comment]
i'd love to have a feature like that. i tried to deploy the script on my own on heroku but the process was a little bit convoluted to me. 
any help of experienced users would be appreciated.

**Comment by forscht** [comment]
@cboRD181 @Ekramhadidi I have added support for Heroku one click deploy button. (Checkout README)
Closing this issue for now. Please reopen it again if you face any difficulties to deploy on Heroku.
