### ISSUE TITLE
[Discussion] Version 4.0

### ISSUE THREAD

**Issue by BrainBursty** [forscht/ddrive#31]
### I want to discuss some changes for version 4.0.
<br />

> #### Switch from JavaScript to [TypeScript](https://www.typescriptlang.org/)
Switching from JavaScript to TypeScript makes it way easier to determine errors in the code and support older Node.JS versions. Furthermore it gives developers that are using DDrive as a library in TypeScript projects full autocompletion and typesafety.
<br />

> #### **Rename the main branch to ``main``, ``bleeding-edge``, ``latest``, ...**
Renaming the main branch everytime a new version comes out just breaks the repository for all developers that are working on it. Also it makes it nearly impossible to reliable use automatic deployment/release systems.
<br />

> #### **Automatically publish new changes**
This goes hand in hand with the previous point. After there is a good naming for the main branch the project can introduce an automatic deployment/release system like [Semantic Release](https://github.com/semantic-release/semantic-release#readme). Which allows to instantly and automatically publish new changes as soon as they are available and reviewed.
<br />

> #### **Fix #21** 
Just fix the bug :)
<br />

> #### **Add #12** 
This is a pretty good suggestion as it's pain how slow ddrive currently is. It can't even use 10% of my potential network speed.
<br />

> #### **Add #29** 
This is a pretty good suggestion too as discord shouldn't see what you are uploading. This is what I would expect by default from any software that wants to store my files.
<br />

**Comment by forscht** [comment]
@BrainBursty Thanks for inputs mate. I am totally booked for few days. I will start working on this once I will get the time. Mean while if you can fix 1 or 2 issues it will be amazing.

**Comment by forscht** [comment]
These improvements has been added in version [v4.0](https://github.com/forscht/ddrive/releases/tag/v4.0.0)
