### ISSUE TITLE
Suggestion - use forums as folders

### ISSUE THREAD

**Issue by Dycool** [forscht/ddrive#34]
Theres a new feature that everyone has probably heard of which is forums, it would be great to use them as folders so it speeds up loading times. (and discord is releasing a 500mb limit for nitro users so pls consider this too).

**Comment by forscht** [comment]
1. Can't use forums as sub folders.
2. It would introduce breaking changes in code and old files metadata won't be sync with it.
3. Planning to move file metadata to separate db in future release
