### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Bedrock16** [forscht/ddrive#37]
Getting this error while hosting it on repl.it
![Screenshot_20221019-101518-616](https://user-images.githubusercontent.com/78468172/196599931-fcfa2fab-4e90-4dfa-b9ce-70aa7e56d901.png)
Intents are also enabled
![Screenshot_20221019-101633](https://user-images.githubusercontent.com/78468172/196599976-fa511dab-1117-4ec3-aa89-ce5545567e7d.png)

**Comment by forscht** [comment]
Delete all the messages from channel and try again, it will work.

**Comment by Bedrock16** [comment]
> Delete all the messages from channel and try again, it will work.

Thank you for help it worked 🙂
