### ISSUE TITLE
Can't upload large files

### ISSUE THREAD

**Issue by berkay-digital** [forscht/ddrive#46]
**I'm not able to upload large files. Ddrive works very good with low file sizes but when i try to upload files more than 250 mb i'm facing an error:**
![image](https://user-images.githubusercontent.com/46861579/205758773-364dbc51-b7d3-4350-b8d5-c66521b52c9e.png)
**I tried increasing the timeout.
I tried uploading different files.**
My network speed:
![image](https://user-images.githubusercontent.com/46861579/205760913-05c757f1-6bcf-468d-a00c-a0510417353f.png)

**Comment by forscht** [comment]
It seems because of your upload speed, What timeout time have you tested?

**Comment by esheodinvopros** [comment]
I have the same problem, can't upload 1GB+ files. I set all available timeout values, but it has no effect.

**Comment by websterwh** [comment]
I have had success uploading 5gb+ files, but my upload speed is also gigabit.

**Comment by berkay-digital** [comment]
**Issue solved.** My NodeJS was v18 so i uninstalled it and installed v16 now its working with every file size.

**Comment by KloudAlpha** [comment]
> It seems because of your upload speed, What timeout time have you tested?

anybody know how to change the timeout value? tried setting an env variable with no luck. I see the API usage in the readme but no idea where that code goes
