### ISSUE TITLE
I keep getting an error with hosting this on Cyclic dot sh

### ISSUE THREAD

**Issue by nickolasio** [forscht/ddrive#50]
[Error] {"message":"Request Entity Too Large"}
Shows in the webpage url I hosted when I try to upload larger files.
I am unsure what is the maximum size allowed, but small files around 3-6MB work fine at least, and when I tried hosting this thing on replit it didn't have this weird problem. Cyclic and node logs do not show anything about the affected file operations.
![image](https://user-images.githubusercontent.com/33207900/208117340-2848d91f-33be-45df-b15d-e4b9e6376fe6.png)

**Comment by forscht** [comment]
Have you modified `chunkSize` option?

**Comment by nickolasio** [comment]
No, I have not

**Comment by forscht** [comment]
It is because cyclic's front-end proxy doesn't support streams and buffers whole file into memory and limited to 6 MB only.
![image](https://user-images.githubusercontent.com/59018146/210775952-98026176-93ec-42e0-893a-71d8e0bf22f5.png)
