### ISSUE TITLE
App crashed, unknown error (docker)

### ISSUE THREAD

**Issue by KloudAlpha** [forscht/ddrive#57]
I can't get the docker container to run anymore. Still works fine with node 16 though.
<img width="721" alt="Screenshot 2023-01-05 at 4 35 21 AM" src="https://user-images.githubusercontent.com/11934011/210748235-3c6352d8-05f9-4ddf-80c6-c31b31d6881d.png">

**Comment by billyboybob** [comment]
tried using replit via the deploy button, same thing.

**Comment by forscht** [comment]
@billyboybob @KloudAlpha Thanks for reporting the issue, It was introduced in last release, which I have fixed in latest release. Take pull and it should work fine. Please close this issue once you test.

**Comment by KloudAlpha** [comment]
Working again, thank you! 
Can't wait to see v4 with some type of db support, boot type is about an hour and increasing. Thank you and contributors for your work. :)
