### ISSUE TITLE
Can't upload files or create folders

### ISSUE THREAD

**Issue by billyboybob** [forscht/ddrive#63]
I tried deploying using Railway, but I cannot upload anything nor create folders. Checking the Postgres logs showed a bunch of the same errors.
![Screenshot_5233](https://user-images.githubusercontent.com/61484364/212440134-10ae7223-22ee-4774-888b-89c6cae7d725.png)

Full log:
[log.txt](https://github.com/forscht/ddrive/files/10416130/log.txt)

**Comment by forscht** [comment]
You need to run migration first on db.

1. Clone repo in local
2. Put `DATABASE_URL={DB_URL}` in `config/.env`
3. Run `npm install`
4. Run `npm run migration:up`
5. Continue using on railway

**Comment by forscht** [comment]
Close issue after you get it working

**Comment by billyboybob** [comment]
It was slightly annoying getting it set up, but I can upload files and create folders now. Thanks!
