### ISSUE TITLE
Can not download files which has Unicode characters in filename.

### ISSUE THREAD

**Issue by MeowIce** [forscht/ddrive#74]
When I try to download a file with Unicode characters in its filename, for example: `ă à ạ ã.zip`, it returns an invalid character set error.
![image](https://user-images.githubusercontent.com/70711319/226391823-dd4f6d46-8b53-488d-9ac4-1d43055ab138.png)
Logs:
```
{"level":50,"time":1679326699626,"err":{"type":"TypeError","message":"Invalid character in header content [\"Content-Disposition\"]","stack":"TypeError [ERR_INVALID_CHAR]: Invalid character in header content [\"Content-Disposition\"]\n    at storeHeader (node:_http_outgoing:532:5)\n    at processHeader (node:_http_outgoing:527:3)\n    at ServerResponse._storeHeader (node:_http_outgoing:421:11)\n    at ServerResponse.writeHead (node:_http_server:369:8)\n    at module.exports.handler (/home/meowice/Downloads/ddrive/src/http/api/routes/file/download.js:75:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","code":"ERR_INVALID_CHAR","reqId":"req-x"},"msg":"Invalid character in header content [\"Content-Disposition\"]"}
{"level":30
```

**Comment by forscht** [comment]
@MeowIce Can you take pull and try again?

**Comment by MeowIce** [comment]
> @MeowIce Can you take pull and try again?

Yes, it can download now but the filename has removed all Unicode chars. Can you keep those chars ?
Filename on DDrive: `ă à ạ ã ả hảy`
Filename after downloaded: `hy`

**Comment by forscht** [comment]
@MeowIce Take pull and try again

**Comment by MeowIce** [comment]
> @MeowIce Take pull and try again

Worked ;)
Thanks for your quick reply and fixes <3
