### ISSUE TITLE
Import File

### ISSUE THREAD

**Issue by mattthhdp** [forscht/ddrive#8]
Is it possible to importe a file stucture ? let's say i have a folder with 2-3 subfoler and a few movie/music, or it's only file by file ?

**Comment by darshan-genea** [comment]
Yes you can use this command,
```sh
./bin/dclone --token {token} --channelId {channelId} --path movies/
```

**Comment by mattthhdp** [comment]
Working perfectly !
Anyway to do it with the UI as some folder are on another computer ?
you rock by the way ^^

**Comment by forscht** [comment]
@mattthhdp You can run same command on another computer as well, it will just merge the folders.
I don't think it's possible to do from UI. Also I don't know much about front end so :(.
Let me know if you find a way.
