### ISSUE TITLE
[Feature Request] Uploading using the cURL or wget

### ISSUE THREAD

**Issue by sidanya** [forscht/ddrive#9]
Is it possible to somehow upload files to the ddrive using a curl command like this:

`curl -T archive.tar.gz http://127.0.0.1:8080/archive.tar.gz`

I searched for a way to do this but only found dclone which is not available on ARM and would like to be able to upload files to the site via cURL or wget.

**Comment by forscht** [comment]
@idanyas It's totally possible with current implementation, try this.
`curl -X POST -T archive.tar.gz http://127.0.0.1:8080/archive.tar.gz`

**Comment by sidanya** [comment]
I didn't know it was possible to upload so easily, thank you.
